version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///contracts.db
    volumes:
      - .:/app
      - ./instance:/app/instance
